apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: favorites-service
  name: favorites-service
spec:
  ports:
    - name: "83"
      port: 83
      targetPort: 83
  selector:
    io.kompose.service: favorites-service
