apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: todo-service
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: todo-service
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "82"
          image: todo-service
          name: todo-service
          ports:
            - containerPort: 82
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: todos-data
      restartPolicy: Always
      volumes:
        - name: todos-data
          persistentVolumeClaim:
            claimName: todos-data
